# Generated by Django 5.0.6 on 2024-05-15 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PublishingHouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("town", models.CharField(max_length=100)),
                ("found_date", models.DateTimeField()),
                ("website_url", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ISBN", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="")),
                ("release_date", models.DateTimeField()),
                ("number_of_pages", models.IntegerField()),
                ("dimensions", models.CharField(max_length=100)),
                (
                    "page_type",
                    models.CharField(
                        choices=[("HA", "HARD"), ("SO", "SOFT")], max_length=2
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ROM", "ROMANCE"),
                            ("THR", "THRILLER"),
                            ("BIO", "BIOGRAPHY"),
                            ("CLA", "CLASSIC"),
                            ("DRA", "DRAMA"),
                            ("HIS", "HISTORY"),
                        ],
                        max_length=3,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "publishing_house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="BookStore.publishinghouse",
                    ),
                ),
            ],
        ),
    ]
