# Generated by Django 5.0.6 on 2024-05-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BookStore", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
